### PR TITLE
Allow usage for inventory variables and indented module parameters.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by franklinkim** [comment]
hi, same here as in this [pull request](https://github.com/weareinteractive/ansible-files/pull/1).
Please provide an example usage and / or see if the other comment would resolve this.

**Comment by ypid** [comment]
And the same answer applies also for franklinkim.cron :smile: See: https://github.com/weareinteractive/ansible-files/pull/1#issuecomment-133691467

**Comment by franklinkim** [comment]
Same, same ;) https://github.com/weareinteractive/ansible-files/pull/1#issuecomment-133702912

**Comment by franklinkim** [comment]
Same as https://github.com/weareinteractive/ansible-files/pull/1#issuecomment-133714152

_I leave this open for voting and if more people want this to be included I'll also check all my other roles to be sync with this feature._

**Pull request closed without merging**
